### PR TITLE
Fixed a few clang warnings by adding 'const'

### PR DESCRIPTION
**Pull request by seanm**
Also fixed a warning about an unused private #define.

### CODE REVIEW

**Comment by seanm** [comment]
Thanks Vlad!  Can you merge this into ITK too?  It will fix some of the dashboard warnings.

**Comment by vfonov** [comment]
mainline itk ?

**Comment by seanm** [comment]
yeah, ITK git master

**Comment by vfonov** [comment]
maybe it's worth making a new release of libminc first?

**Comment by seanm** [comment]
I leave that up to you... I just wanted to cleanup up my ITK dashboard a bit...

**Comment by seanm** [comment]
So Vlad did you decide to do a new release and/or merge into ITK?

**Comment by vfonov** [comment]
Didn't have time for either, unfortunately. Yet.

By the way, for my installations I am compiling libminc out of ITK and 
then specify it as system library (the same goes for HDF5).

**Pull request merged**
