### PR TITLE
COMP:  Enable CMP0063 NEW, support setting visibility properties

### PR DESCRIPTION
**Pull request by blowekamp**
Enables setting default C_VISIBILITY_PRESET to hidden to reduce the
size of libraries.

### CODE REVIEW

**Comment by blowekamp** [comment]
This patch was made for ITK:
http://review.source.kitware.com/#/c/22928/1

**Comment by thewtex** [comment]
Please make the PR against the `develop` branch.

**Comment by blowekamp** [comment]
Do you mean the patch's parent should be the `develop` branch or the develop branch to be the target to merge into?

**Comment by thewtex** [comment]
The `develop` branch should be the target of the merge.

**Comment by blowekamp** [comment]
Done, `develop` targeted.

But there appears to be some CI problems not related to this patch.

**Pull request merged**
