### PR TITLE
Url updates

### PR DESCRIPTION
**Pull request by seanm**

### CODE REVIEW

**Comment by seanm** [comment]
@vfonov care to review?

**Review by vfonov — COMMENTED** [review]
I have sha256  0adbc0eacafecabeb3ad2ebe64f4ef7fdad4f33e12b5bbf6630a8c37a72db1a9 for hdf5-1.8.7.tar.gz

**Review by vfonov — APPROVED** [review]

**Review by vfonov — APPROVED** [review]

**Review by vfonov — APPROVED** [review]

**Comment by seanm** [comment]
> I have sha256 0adbc0eacafecabeb3ad2ebe64f4ef7fdad4f33e12b5bbf6630a8c37a72db1a9 for hdf5-1.8.7.tar.gz

That's weird. I thought I was very careful. I've just been trying to figure out what happened and it seems that I get different files from different apps!  I downloaded with Firefox, Safari, Chromium, and curl:

```
MD5 (/Users/sean/test/chromium/hdf5-1.8.7.tar.gz) = 37711d4bcb72997e93d495f97c76c33a
MD5 (/Users/sean/test/curl/hdf5-1.8.7.tar.gz) = 37711d4bcb72997e93d495f97c76c33a
MD5 (/Users/sean/test/FF/hdf5-1.8.7.tar.gz) = 136266ff3a47981487ebd9fc342c2bb2
MD5 (/Users/sean/test/safari/hdf5-1.8.7.tar.gz) = 136266ff3a47981487ebd9fc342c2bb2
```

The HDF5 website publishes an md5 here: https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8/hdf5-1.8.7/src/hdf5-1.8.7.tar.md5 but its for the tar, not the gz:

`36d22e228334f49e82dcddd04af0025e  hdf5-1.8.7.tar`

So I used `gunzip` on my 4 downloads and the get:

```
MD5 (/Users/sean/test/chromium/hdf5-1.8.7.tar) = 36d22e228334f49e82dcddd04af0025e
MD5 (/Users/sean/test/curl/hdf5-1.8.7.tar) = 36d22e228334f49e82dcddd04af0025e
MD5 (/Users/sean/test/FF/hdf5-1.8.7.tar) = 37711d4bcb72997e93d495f97c76c33a
MD5 (/Users/sean/test/safari/hdf5-1.8.7.tar) = 37711d4bcb72997e93d495f97c76c33a
```

After untaring, all 4 resulting folders are identical.  Weird.

I guess we should use the curl result then, since CMake uses curl I believe.

**Comment by seanm** [comment]
OK, that also explains why the md5 in the .cmake file for the old HDF5 URL didn't match the md5 of the file I downloaded at the new URL.  They do match with curl.  So this proves that new URL is still pointing to the same release as before.  Phew.

**Pull request merged**
