### PR TITLE
Fixes to various clang warnings, increased minimum CMake version

### PR DESCRIPTION
**Pull request by seanm**

### CODE REVIEW

**Comment by seanm** [comment]
@vfonov apologies for so many commits, but each is small. I thought it best to do 1 comment per warning flag.

Please review carefully. I'm no expert in this codebase!

**Comment by gdevenyi** [comment]
Looks good to me. @seanm does this all pass `make test`?

An expanded testing swapping this patched version in the minc-toolkit-v2 superbuild tests would also be welcome.

**Comment by seanm** [comment]
> Looks good to me. @seanm does this all pass `make test`?

No, but neither does it before this PR. For me, the same tests fail before and after.

**Comment by vfonov** [comment]
> Is this the case for everyone?

`100% tests passed, 0 tests failed out of 54` on linux

**Comment by seanm** [comment]
Running one of the tests has a lot of HDF5 messages, I wonder if this isn't a linux vs macOS difference, but rather a due to different HDF5 versions. What version are you using?  I'm using from git master.

**Comment by seanm** [comment]
OK I'll try the same version...

**Comment by seanm** [comment]
```
    Start 28: verify_xfm_1

28: Test command: /Users/sean/external/libminc-bin/testdir/verify_xfm "/Users/sean/external/libminc/testdir/vio_xfm_test/t3.xfm" "/Users/sean/external/libminc/testdir/vio_xfm_test/random2" "1e-6"
28: Working Directory: /Users/sean/external/libminc-bin/testdir
28: Test timeout computed to be: 1500
28: HDF5-DIAG: Error detected in HDF5 (1.14.3) thread 0:
28:   #000: /Users/sean/external/hdf5-1.14.3/src/H5D.c line 1061 in H5Dread(): can't synchronously read data
28:     major: Dataset
28:     minor: Read failed
28:   #001: /Users/sean/external/hdf5-1.14.3/src/H5D.c line 1008 in H5D__read_api_common(): can't read data
28:     major: Dataset
28:     minor: Read failed
28:   #002: /Users/sean/external/hdf5-1.14.3/src/H5VLcallback.c line 2092 in H5VL_dataset_read_direct(): dataset read failed
28:     major: Virtual Object Layer
28:     minor: Read failed
28:   #003: /Users/sean/external/hdf5-1.14.3/src/H5VLcallback.c line 2048 in H5VL__dataset_read(): dataset read failed
28:     major: Virtual Object Layer
28:     minor: Read failed
28:   #004: /Users/sean/external/hdf5-1.14.3/src/H5VLnative_dataset.c line 373 in H5VL__native_dataset_read(): can't read data
28:     major: Dataset
28:     minor: Read failed
28:   #005: /Users/sean/external/hdf5-1.14.3/src/H5Dio.c line 401 in H5D__read(): can't read data
28:     major: Dataset
28:     minor: Read failed
28:   #006: /Users/sean/external/hdf5-1.14.3/src/H5Dchunk.c line 2919 in H5D__chunk_read(): unable to read raw data chunk
28:     major: Low-level I/O
28:     minor: Read failed
28:   #007: /Users/sean/external/hdf5-1.14.3/src/H5Dchunk.c line 4548 in H5D__chunk_lock(): data pipeline read failed
28:     major: Dataset
28:     minor: Filter operation failed
28:   #008: /Users/sean/external/hdf5-1.14.3/src/H5Z.c line 1355 in H5Z_pipeline(): required filter 'deflate' is not registered
28:     major: Data filters
28:     minor: Read failed
28:   #009: /Users/sean/external/hdf5-1.14.3/src/H5PLint.c line 267 in H5PL_load(): can't find plugin. Check either HDF5_VOL_CONNECTOR, HDF5_PLUGIN_PATH, default location, or path set by H5PLxxx functions
28:     major: Plugin for dynamically loaded library
28:     minor: Object not found
28:   #010: /Users/sean/external/hdf5-1.14.3/src/H5PLpath.c line 804 in H5PL__find_plugin_in_path_table(): search in path /usr/local/hdf5/lib/plugin encountered an error
28:     major: Plugin for dynamically loaded library
28:     minor: Can't get value
28:   #011: /Users/sean/external/hdf5-1.14.3/src/H5PLpath.c line 857 in H5PL__find_plugin_in_path(): can't open directory (/usr/local/hdf5/lib/plugin). Please verify its existence
28:     major: Plugin for dynamically loaded library
28:     minor: Can't open directory or file
28: /Users/sean/external/libminc/libsrc/hdf_convenience.c:1557 (from miicv_get): Can't read dataset /minc-2.0/image/0/image
28: /Users/sean/external/libminc/volume_io/Prog_utils/print.c:226 (from miicv_free): volume_io error: input_transform: error reading transform.
28:
28: Failed to load transform '/Users/sean/external/libminc/testdir/vio_xfm_test/t3.xfm'
1/1 Test #28: verify_xfm_1 .....................***Failed    0.01 sec
```

Is it maybe just that I'm supposed to have a `minc-2.0/image/0/image` file somewhere?

**Comment by gdevenyi** [comment]
> Is it maybe just that I'm supposed to have a minc-2.0/image/0/image file somewhere?

No `minc-2.0/image/0/image` is part of the MINC namespace in a MINC file.

The errors look like your HDF5 is installed in `/Users/sean/external/hdf5-1.14.3` but it looks like its trying to load its plugins from `/usr/local/hdf5/lib/plugin` and can't find deflate which is used for the internal compression inside MINC files.

**Comment by vfonov** [comment]
So, I merged most of the commits into develop. The only one that is problematic is https://github.com/BIC-MNI/libminc/pull/126/commits/9849b33f3f0551a9033679e1faa2f76ad3bef39c - those checks still needed on Linux, in particular because there is a difference between Apple and Linux there.

**Comment by seanm** [comment]
> can't find deflate which is used for the internal compression inside MINC files.

Ah, so this might be because configuring HDF5 was not finding my zlib, so I built without zlib support.  HDF5 has a variable `ZLIB_DIR` with the description "ZLIB_DIR: The directory containing a CMake configuration file for ZLIB." which is annoying because macOS ships with zlib libraries and headers, but not a cmake config file.  It's strange that HDF5, unlike say vtk and itk and other libraries, doesn't seem to have variables to just point to the zlib library file and headers folder.  I'll take this up with them...

>The only one that is problematic is https://github.com/BIC-MNI/libminc/commit/9849b33f3f0551a9033679e1faa2f76ad3bef39c - those checks still needed on Linux

Do you recall which?

>probably, if we ignore one unaccepted commit.

Sure, we can close this now.

**Comment by dzenanz** [comment]
I cannot close this. Either PR author or someone with write permission here needs to do it.

**Comment by seanm** [comment]
> It's strange that HDF5, unlike say vtk and itk and other libraries, doesn't seem to have variables to just point to the zlib library file and headers folder. I'll take this up with them...

Created: https://github.com/HDFGroup/hdf5/issues/5155

**Comment by vfonov** [comment]
> Do you recall which?
> 
> >
`strings.h` is needed on linux.

**Pull request closed without merging**
