### PR TITLE
Removed checks for long-standard or long-obsolete header files

### PR DESCRIPTION
**Pull request by seanm**
Many of these header have been standardized since C89, others have been obsolete forever.

### CODE REVIEW

**Comment by seanm** [comment]
@vfonov ah, previously I had removed the actual `#include <strings.h>` which was indeed wrong, it was only the `#if HAVE_STRINGS_H` that I can hopefully remove. It's actually Windows I'm not sure about now...

**Comment by seanm** [comment]
Yeah, I think `strings.h` is from POSIX so probably not available on Windows...

**Comment by vfonov** [comment]
`strings.h` is also not available on MacOS, is it?

**Comment by seanm** [comment]
> `strings.h` is also not available on MacOS, is it?

No, it is available on macOS. According to macOS man page:

```
     The strcasecmp() and strncasecmp() functions first appeared in
     4.4BSD.  Their prototypes existed previously in <string.h> before
     they were moved to <strings.h> for IEEE Std 1003.1-2001 (“POSIX.1”)
     compliance.
```

So that's the standard header for these standard POSIX functions. But Windows in not POSIX... :(

**Comment by seanm** [comment]
OK, I brought the `strings.h` check back. Hopefully this is good now.

**Pull request merged**
