### PR TITLE
miconvert_voxel_to_real: Ignore scaling for float volumes

### PR DESCRIPTION
**Pull request by cfhammill**
Adds the float check and a test that it works.

### CODE REVIEW

**Comment by cfhammill** [comment]
should solve #108

**Comment by gdevenyi** [comment]
Awesome thanks @cfhammill !

**Comment by cfhammill** [comment]
No problem, travis failure looks unrelated to this PR.

**Comment by gdevenyi** [comment]
Tests all pass locally, so it has something to do with the build/build environment on Travis.

**Comment by vfonov** [comment]
looks ok

**Pull request merged**
